app:
  name: "iFall"
  version: "1.0.0"
  env: "${APP_ENV}"
  logPath: ""

server:
  host: "0.0.0.0"
  port: "${SERVER_PORT}"
  requestTimeout: 10s
  closeTimeout: 30s

storage:
  pingTimeout: 5s
  path: "/storage/storage.db"

email:
  name: "iPhone Price Check"
  address: "${EMAIL_ADDRESS}"
  password: "${EMAIL_PASSWORD}"
  smtpAddress: "smtp.gmail.com"
  smtpServerAddress: "smtp.gmail.com:587"

apiClient:
  baseURL: "https://newton.by/mobilnye-telefony"
  timeout: 10s

scheduler:
  hour: 15
  minute: 34
  emailSupp: false

iphones:
  black: "apple_iphone_17_256gb_chernyy"
  blue: "apple_iphone_17_256gb_goluboy"
  white: "apple_iphone_17_256gb_belyy"
  green: "apple_iphone_17_256gb_zelenyy"
  pink: "apple_iphone_17_256gb_sirenevyy"
  blackEsim: "apple_iphone_17_dual_esim_256gb_chernyy"
  blueEsim: "apple_iphone_17_dual_esim_256gb_goluboy"
  pinkEsim: "apple_iphone_17_dual_esim_256gb_sirenevyy"
  timeout: 5s

telegramBot:
  token: "${TELEGRAM_BOT_TOKEN}"
  timeout: 10s
  